$spritename    explo
$type          vp_parallel
$texture       additive
$load		explo0.bmp
$frame		0   0   256   256
$load		explo1.bmp
$frame		0   0   256   256
$load		explo2.bmp
$frame		0   0   256   256
$load		explo3.bmp
$frame		0   0   256   256
$load		explo4.bmp
$frame		0   0   256   256
$load		explo5.bmp
$frame		0   0   256   256
$load		explo6.bmp
$frame		0   0   256   256
$load		explo7.bmp
$frame		0   0   256   256
$load		explo8.bmp
$frame		0   0   256   256
$load		explo9.bmp
$frame		0   0   256   256
$load		explo10.bmp
$frame		0   0   256   256
$load		explo11.bmp
$frame		0   0   256   256
